Repository Nordix/Meridio, pull requests merged in 2023-10, with the labels that each got.

#459 operator; fix mount path of resource templates
  config/operator/patches/operator_resource_templates_patch.yaml
Labels: kind/bug, size/S, concept/trench, concept/conduit, concept/attractor, area/configuration

#462 Release v1.0.12 (Documentation)
  test/e2e/environment/kind-operator/test-scope.yaml
  website/src/pages/versions.md
Labels: kind/documentation

#463 Fix env variable reconciler
  pkg/controllers/attractor/nse-vlan.go
  pkg/controllers/attractor/stateless-lb-frontend.go
  pkg/controllers/common/models.go
  pkg/controllers/common/models_test.go
  pkg/controllers/conduit/proxy.go
  pkg/controllers/trench/ipam.go
  pkg/controllers/trench/nsp.go
Labels: kind/bug, component/operator

#464 Fix CVE-2023-39325, CVE-2023-3978 and CVE-2023-44487
  Makefile
  build/base-image/Dockerfile
  examples/target/go.mod
  examples/target/go.sum
  go.mod
  go.sum
Labels: area/security

#465 operator; BGP ports default to 179
  api/v1/gateway_types.go
  config/crd/bases/meridio.nordix.org_gateways.yaml
Labels: size/S, concept/gateway, area/configuration, component/operator

#461 NSM uplift to v1.11.0
  config/templates/charts/meridio/values.yaml
  deployments/helm/values.yaml
  docs/demo/deployments/nsm/values.yaml
  examples/target/go.mod
  examples/target/go.sum
  go.mod
  go.sum
  pkg/controllers/attractor/nse-vlan.go
  pkg/controllers/attractor/stateless-lb-frontend.go
  test/e2e/environment/kind-operator/test-scope.yaml
Labels: kind/enhancement

#472 Fix GHSA-m425-mq94-257g
  build/base-image/Dockerfile
  examples/target/go.mod
  examples/target/go.sum
  go.mod
  go.sum
Labels: area/security
