Repository Nordix/Meridio, pull requests merged in 2023-08, with the labels that each got.

#448 TAPA; sync interface name cache for recovered connections
  pkg/ambassador/tap/conduit/conduit.go
  pkg/nsm/interfacename/cache.go
  pkg/nsm/interfacename/cache_test.go
  pkg/nsm/interfacename/client_test.go
  pkg/nsm/interfacename/common.go
  pkg/nsm/interfacename/generator.go
  pkg/nsm/interfacename/server_test.go
Labels: kind/bug, priority/high, size/M, component/TAPA

#449 Fix CVE-2023-3978
  examples/target/go.mod
  examples/target/go.sum
  go.mod
  go.sum
  pkg/nsm/endpoint/expirationtime/nse_client.go
Labels: area/security

#450 Update to golang 1.21
  build/frontend/Dockerfile
  build/ipam/Dockerfile
  build/nsp/Dockerfile
  build/operator/Dockerfile
  build/proxy/Dockerfile
  build/stateless-lb/Dockerfile
  build/tapa/Dockerfile
  examples/target/build/example-target/Dockerfile
  examples/target/go.mod
  examples/target/go.sum
  go.mod
  go.sum
Labels: kind/enhancement, priority/low, size/S
