Repository Nordix/Meridio, pull requests merged in 2023-03, with the labels that each got.

#389 Fix Linter for golang 1.20
  Makefile
Labels: area/CI

#387 Monitor NSM connection in TAPA to get latest local IPs
  cmd/tapa/main.go
  pkg/ambassador/tap/conduit/conduit.go
  pkg/ambassador/tap/conduit/conduit_test.go
  pkg/ambassador/tap/tap.go
  pkg/ambassador/tap/trench/factory.go
  pkg/ambassador/tap/trench/trench.go
Labels: kind/bug, component/TAPA

#385 proxy; TAPA connection IPs stored in IPAM using TAPA side ID as key
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
Labels: kind/bug, concept/conduit, NBC, area/networking, component/proxy, component/TAPA

#360 Log contents of interface objects
  pkg/loadbalancer/stream/loadbalancer.go
  pkg/loadbalancer/stream/target.go
Labels: kind/bug

#390 Fix VIPs used as local IPs in TAPA
  cmd/proxy/internal/client/fullmesh.go
  pkg/ambassador/tap/conduit/conduit.go
  pkg/ambassador/tap/conduit/conduit_test.go
Labels: kind/bug, priority/high, component/TAPA

#374 Fix CVE-2022-41723
  build/base-image/Dockerfile
  examples/target/go.mod
  examples/target/go.sum
  go.mod
  go.sum
Labels: area/security

#381 NSM uplift to v1.8.0
  config/templates/charts/meridio/values.yaml
  deployments/helm/values.yaml
  docs/demo/deployments/nsm/values.yaml
  go.mod
  go.sum
  pkg/controllers/attractor/nse-vlan.go
  pkg/controllers/attractor/stateless-lb-frontend.go
  test/e2e/environment/kind-operator/test-scope.yaml
Labels: kind/enhancement

#394 Update base-image version and operator base-image
  build/base-image/Dockerfile
  build/operator/Dockerfile
  config/operator/operator.yaml
Labels: kind/enhancement, size/S, component/operator

#357 Update to Go 1.20
  Makefile
  build/frontend/Dockerfile
  build/ipam/Dockerfile
  build/nsp/Dockerfile
  build/operator/Dockerfile
  build/proxy/Dockerfile
  build/stateless-lb/Dockerfile
  build/tapa/Dockerfile
  examples/target/build/example-target/Dockerfile
  examples/target/go.mod
  go.mod
  pkg/ambassador/tap/stream/stream.go
  pkg/nsm/interfacename/generator.go
Labels: kind/enhancement, priority/low, size/S

#397 Fix make generate, log-collector
  Makefile
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  hack/boilerplate.go.txt
  hack/helm-chart/generator.sh
  hack/log_collector.sh
Labels: kind/enhancement, area/CI

#396 Fix CVE-2023-24535
  build/base-image/Dockerfile
Labels: area/security
