Repository Nordix/Meridio, pull requests merged in 2024-02, with the labels that each got.

#499 metrics; fix collecting flow stats
  pkg/loadbalancer/flow/metrics.go
Labels: kind/bug, size/S, component/stateless-lb

#477 Gateway routes imported/exported/preferred metrics
  cmd/frontend/internal/frontend/metrics.go
  cmd/frontend/internal/frontend/metrics_test.go
  cmd/frontend/internal/frontend/service.go
  cmd/frontend/main.go
  docs/observability/dashboard.json
  docs/observability/metrics.md
  pkg/metrics/const.go
Labels: kind/enhancement, concept/gateway, component/front-end

#504 Update to golang 1.22
  Makefile
  api/v1/attractor_webhook.go
  api/v1/conduit_webhook.go
  api/v1/flow_webhook.go
  api/v1/gateway_webhook.go
  api/v1/stream_webhook.go
  api/v1/trench_webhook.go
  api/v1/vip_webhook.go
  api/v1/webhook_suite_test.go
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  build/frontend/Dockerfile
  build/ipam/Dockerfile
  build/nsp/Dockerfile
  build/operator/Dockerfile
  build/proxy/Dockerfile
  build/stateless-lb/Dockerfile
  build/tapa/Dockerfile
  cmd/operator/main.go
  config/crd/bases/meridio.nordix.org_attractors.yaml
  config/crd/bases/meridio.nordix.org_conduits.yaml
  config/crd/bases/meridio.nordix.org_flows.yaml
  config/crd/bases/meridio.nordix.org_gateways.yaml
  config/crd/bases/meridio.nordix.org_streams.yaml
  config/crd/bases/meridio.nordix.org_trenches.yaml
  config/crd/bases/meridio.nordix.org_vips.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  docs/demo/scripts/kind/Makefile
  examples/target/build/example-target/Dockerfile
  examples/target/go.mod
  examples/target/go.sum
  go.mod
  go.sum
  pkg/controllers/trench/trench_controller.go
  test/integration/attractor_test.go
  test/integration/e2e_suite_test.go
  test/integration/gateway_test.go
Labels: kind/enhancement

#506 Update minimum Kernel version supported to 5.15
  readme.md
Labels: kind/documentation

#505 Fix X509 source leak in credentials pkg
  pkg/security/credentials/credentials.go
Labels: kind/bug

#503 TAPA; fix goroutine cleanup in intefacename cache
  pkg/nsm/interfacename/cache.go
  pkg/nsm/interfacename/cache_test.go
Labels: kind/bug, component/TAPA
